config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  resources :posts, only: %i[new create destroy]
  resources :comments, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_presence_of :comment
  validates_presence_of :user_id
  validates_presence_of :post_id
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sent_to, class_name: "User", foreign_key: "sent_to_id"
  belongs_to :sent_by, class_name: "User", foreign_key: "sent_by_id"
  scope :friends, -> { where("status =?", true) }
  scope :not_friends, -> { where("status =?", false) }
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates_uniqueness_of :post_id, scope: :user_id

	after_create :increase_post_like_counter
	after_destroy :decrease_post_like_counter

	private

	def increase_post_like_counter
		Post.find(self.post_id).increment(:total_likes_count).save	
	end

	def decrease_post_like_counter
		Post.find(self.post_id).decrement(:total_likes_count).save	
	end
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :likes
	has_many :comments

	mount_uploader :image, ImageUploader
	default_scope -> { order(created_at: :desc) }

	scope :active, -> { where active: true }
	before_create :set_active

  private

  def set_active
  	self.active = true
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

  has_many :posts, dependent:   :destroy
  has_many :likes
  has_many :friend_request_sent, class_name: 'Friendship',
                                 foreign_key: 'sent_by_id',
                                 dependent: :destroy
  has_many :friend_request_receive, class_name: 'Friendship',
                                    foreign_key: 'sent_to_id',
                                    dependent: :destroy
  has_many :friends, -> { merge(Friendship.friends) },
            through: :friend_request_sent, source: :sent_to
  has_many :pending_requests, -> { merge(Friendship.not_friends) },
            through: :friend_request_sent, source: :sent_to    
  has_many :received_requests, -> { merge(Friendship.not_friends) },
            through: :friend_request_receive, source: :sent_by

	def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected	
  
  def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name email password image image_cache])
		devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name email password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id if user_signed_in?
    if @comment.save
      redirect_to root_path, flash: { success: 'Comment was created successfully' }
    else
      redirect_to root_path, flash: { danger: 'Comment was not created' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  include ApplicationHelper
  def create
    @friendship = current_user.friend_request_sent.build(sent_to_id: params[:user_id])
    if @friendship.save
      flash[:success] = 'Friend Request Sent!'
    else
      flash[:danger] = 'Friend Request Failed!'
    end
    redirect_to root_path
  end

  def accept_friend
    @friendship = Friendship.find_by(sent_by_id: params[:user_id], sent_to_id: current_user.id, status: false)
    return unless @friendship

    @friendship.status = true

    if @friendship.save
      flash[:success] = 'Friend Request Accepted!'
      @friendship2 = current_user.friend_request_sent.build(sent_to_id: params[:user_id], status: true)
      @friendship2.save
    else
      flash[:danger] = 'Friend Request could not be accepted!'
    end
    redirect_to root_path
  end

  def decline_friend
    @friendship = Friendship.find_by(sent_by_id: params[:user_id], sent_to_id: current_user.id, status: false)
    return unless @friendship
    
    @friendship.destroy
    flash[:success] = 'Friend Request Declined!'
    redirect_to root_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ActionController::Base

  def save_like
    @like = Like.new(post_id: params[:post_id], user_id: current_user.id)
    @post_id = params[:post_id]
    existing_like = Like.where(post_id: @post_id, user_id: current_user.id)
    respond_to do |format|
      format.js{
        if existing_like.any?
          existing_like.first.destroy
          @success = false
        elsif @like.save
          @success = true
        else
          @success = false
        end
        @post_likes = Post.find(@post_id).total_likes_count
        render 'posts/like'
        }
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id if user_signed_in?
		if @post.save
			redirect_to root_path, flash: { success: 'Post was created' }
		else
			redirect_to new_post_path, flash: { success: 'Post was not created' }
		end
	end

	def destroy
		@post = Post.find(params[:id])
		return unless current_user.id == @post.user_id

		@post.destroy
		flash[:success] = 'Post deleted'
		redirect_back(fallback_location: root_path)
	end

	private

	def post_params
		params.require(:post).permit(:content, :image, :image_cache)
	end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def index
    @posts = Post.active
    @comment = Comment.new
    @users = User.all
    @friends = current_user.friends
    @pending_requests = current_user.pending_requests
    @friend_requests = current_user.received_requests
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.active
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def friend_request_sent?(user)
    current_user.friend_request_sent.exists?(sent_to_id: user.id)
  end
  
  def friend_request_received?(user)
    current_user.friend_request_receive.exists?(sent_by_id: user.id)
  end
  
  def possible_friend?(user)
    request_sent = current_user.friend_request_sent.exists?(sent_to_id: user.id)
    request_received = current_user.friend_request_receive.exists?(sent_by_id: user.id)
    return true if request_sent != request_received
    return true if request_sent == request_received && request_sent == true
    return false if request_sent == request_received && request_sent == false
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_liked_by_user?(post_id)
		Like.where(post_id: post_id, user_id: current_user.id).any?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<li class="nav-item">
  <%= link_to "Find Friends", users_path, :class => "nav-link"  %>
</li>
<li class="nav-item">
  <%= link_to "New Post", new_post_path, :class => "nav-link"  %> 
</li>
<li class="nav-item">
  <%= link_to "My Profile", user_path(current_user), :class => "nav-link"  %>  
</li>

<li class="nav-item">
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link"  %> 
</li> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendbook</title>
    
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Friends Book</title>
        
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>  
          </button>
           
        </div>  
        <div class="collapse navbar-collapse"id="myNavbar">
          <ul class="nav navbar-nav">
              <%= render 'layouts/header' %>
          </ul>
        </div>
      </div>
    </nav>
  <% end %> 

  <!--   page content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-left">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>        
      </div>
    </div>
    
  </div>



    
  </body>
</html>

app/views/posts/_comments.html.erb
<% post.comments.each do |comment| %>
	<div class="comments">
		
		<strong><%= comment.user.full_name %></strong>
		<%= comment.comment %>
		<p class=""text-muted><%= time_ago_in_words comment.created_at %> ago</p>
	</div>

<% end %>

app/views/posts/_form.html.erb
<div class="container">
<%= form_for @post, html: { multipart: true} do |f| %>
    
  <div class="form-group">
    <%= f.label :Image %><br/>
    <%= f.file_field :image , :class => "form-control"%>
    <%= f.hidden_field :image_cache , :class => "form-control" %>
  </div>

  <br/>

  <div class="form-group">
    <%= f.label :Description %><br/>
    <%= f.text_area :content, :class => "form-control" %>
  </div>

    <%= f.submit "Save Post", :class => "btn btn-success" %>
<% end %>
</div>

app/views/posts/like.js.erb
<% if @success == true %>
	$(".like-<%= @post_id %>").addClass("active");
<% else %>
	$(".like-<%= @post_id %>").removeClass("active");
<% end %>

$("#post-<%= @post_id %>-likes").text("<%= @post_likes %> likes");

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render "form" %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col md-4">
      <% @posts.each do |post|%>
        <div style="margin-top: 2% ">

          <% if post.user.image.url %>
            <%= image_tag post.user.image.url, width: "50px", height: "50px" %>
          <% else %>
            <%= image_tag "1.jpg", width: "50px", height: "50px" %>
          <% end %>
          <%= link_to post.user.full_name, user_path(post.user) %>

        </div>
        <% if current_user.id == post.user_id %>
            <%= link_to post_path(post), method: :delete, data: { confirm: "You sure?" } do %>
              <i class="fa fa-trash hover-red"></i>
            <% end %>
          <% end %>
        
        <div style="margin-top: 2% ">
          <div>
            <%= simple_format post.content %>
          </div>
            <%= image_tag post.image.url , width: "400px", height: "400px" %> 
          <div>
          
          <div class="post-actions">

            <i class= "fa fa-thumbs-up like-<%= post.id %> <%= 'active' if post_liked_by_user?(post.id) %> fa-2x post-like" data-id="<%= post.id %>" aria-hidden="true"></i>
    
          </div>
          <p><strong style="margin-left: 15px;" id="post-<%= post.id %>-likes"><%= post.total_likes_count %>  Likes</strong></p>
          <i><p class="text-muted"><%= time_ago_in_words post.created_at %> ago</p></i> 

          

          <%= render "posts/comments", post: post %>
        
          <div class="comment-box">
            <%= form_for @comment do |f| %>
              <%= f.hidden_field :post_id, value: post.id %> 
              <%= f.text_field :comment, placeholder: "Add comment here......", class:"form-control post-comment" %>
              <%= f.submit "Post", class:"btn btn-success float-right" %>
            <% end %>
          </div>

          </div>
        </div>

      <% end %>
    </div>
  </div>


  <div class="col md-4">   

  <% unless @friends.empty? %>
    <div>
      <h2>My Friends</h2><br> 
      <% @friends.each do |user|%> 
        <div>
          <%= link_to user_path(user) do %>
            <%= user.full_name %>
          <% end %>
          <button class= "btn btn-friend shadow"> Friend </button>
        </div>
      <% end %>
    </div>
  <% end %>

  <% unless @pending_requests.empty? %>
    <div>
      <h2>Sent Friend Requests</h2><hr> 
      <% @pending_requests.each do |user|%>
        <div> 
          <%= link_to user_path(user) do %>
            <%= user.full_name %>
          <% end %>
          <button class= "btn btn-secondary shadow" disabled> Friend Request pending... </button>
        </div>        
      <% end %>
    </div>
  <% end %>

  <% unless @friend_requests.empty? %>
    <div>
        <h2>Pending Friend Requests</h2><hr> 
        <% @friend_requests.each do |user|%>          
            <div> 
              <%= link_to user_path(user) do %>
              <%= user.full_name %>
              <% end %>

              <%= link_to accept_friend_user_friendships_path(user) do %>
                <button type="button" class="btn btn-accept"></i> Accept</button>
              <% end %>
              <%= link_to decline_friend_user_friendships_path(user) do %>
                <button type="button" class="btn btn-decline"></i> Decline</button>
              <% end %>

            </div>    
        <% end %>
    </div>
  <% end %>


  <div>
    <h2>All Users</h2> 
    <% @users.each do |user|%>
      <% if current_user.id != user.id%>
        <% unless possible_friend?(user) %>
          <div> 
            <%= link_to user_path(user) do %>
              <%= user.full_name %>
            <% end %> 
            <%= link_to user_friendships_path(user), method: :post do %>
              <button class= "btn btn-user "> Send Friend Request? </button>
            <% end %>
          </div>
        <%end%>
      <% end %>
    <% end %>
  </div>
</div>

</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col md-4">

      <% if @user.image_url %>
        <%= image_tag @user.image_url, width:"200px",height:"200px", class:"image" %>
      <% else %>
      <%= image_tag "1.jpg", width:"200px",height:"200px"  %>
      <% end %>
      

    </div>
    <div class="col md-8">
      <h1><%= @user.full_name %></h1>
   
      <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-default" if @user.id == current_user.id %> 
 
      <div><%= @user.posts.count %> Posts</div>
</div>
</div>

<div class="container">
    <div class="row">
      <% @posts.each do |post| %>
          

      <div class="col-md-3"  style="margin-top: 20px;margin-left: 20px;">
        
            <%=  image_tag post.image_url, width: "100%", height: "250px" %>
      </div>
      <% end %>
    </div>
  </div>